package com.smsforwarder.oppo.network

import android.content.SharedPreferences
import okhttp3.Interceptor
import okhttp3.Response
import javax.inject.Inject
import javax.inject.Named

/**
 * OkHttp interceptor that attaches the device's API key to every request.
 *
 * The API key is generated by the backend during [ApiService.registerDevice]
 * and stored in [EncryptedSharedPreferences]. It is a randomly generated
 * secret token that identifies and authenticates this OPPO device.
 *
 * SECURITY:
 *   - The key is stored only in EncryptedSharedPreferences (AES-256-GCM).
 *   - It is transmitted over TLS (enforced by network_security_config.xml).
 *   - If no key is stored yet (pre-registration), the header is omitted —
 *     the registerDevice endpoint does not require authentication.
 *   - The key is NEVER logged (logging interceptor is HEADERS-only).
 */
class AuthInterceptor @Inject constructor(
    @Named("encrypted") private val prefs: SharedPreferences
) : Interceptor {

    override fun intercept(chain: Interceptor.Chain): Response {
        val apiKey = prefs.getString(PREF_API_KEY, null)

        val request = if (apiKey != null) {
            chain.request().newBuilder()
                .header("Authorization", "Bearer $apiKey")
                .build()
        } else {
            chain.request() // No key yet — pre-registration
        }

        return chain.proceed(request)
    }

    companion object {
        const val PREF_API_KEY = "device_api_key"
    }
}
