package com.smsforwarder.samsung.network

import okhttp3.Interceptor
import okhttp3.Response
import android.content.SharedPreferences
import javax.inject.Inject
import javax.inject.Named

/**
 * OkHttp interceptor for Samsung app — identical logic to OPPO's [AuthInterceptor].
 *
 * Attaches the Samsung device's API key as a Bearer token to every request.
 * The key is generated by the backend during device registration and stored
 * in [EncryptedSharedPreferences].
 */
class SamsungAuthInterceptor @Inject constructor(
    @Named("encrypted") private val prefs: SharedPreferences
) : Interceptor {

    override fun intercept(chain: Interceptor.Chain): Response {
        val apiKey = prefs.getString(PREF_API_KEY, null)
        val request = if (apiKey != null) {
            chain.request().newBuilder()
                .header("Authorization", "Bearer $apiKey")
                .build()
        } else {
            chain.request()
        }
        return chain.proceed(request)
    }

    companion object {
        const val PREF_API_KEY = "device_api_key"
    }
}
